// Dados simulados dos estabelecimentos, unidades e recursos. Ver o comentário
// no topo de src/lib/seed-data.ts para o contexto geral dos tenants de demonstração.

import { addDays } from "date-fns";
import { obterDefinicaoPlano } from "../planos";
import type { Estabelecimento, Recurso, Unidade } from "../types";
import {
  DIAS_SEG_A_SAB,
  DIAS_SEG_A_SEX,
  DIAS_TER_A_SAB,
  TENANT_BARBEARIA_JR,
  TENANT_BARBEARIA_VINTAGE,
  TENANT_BARBEIRO_BASTIAO,
  TENANT_CLINICA_SORRISO_LEVE,
  TENANT_CORTE_CERTO,
  TENANT_DOM_NAVALHA,
  regrasPadrao,
} from "./shared";

export function gerarEstabelecimentosSeed(): Estabelecimento[] {
  return [
    {
      id: "estab-dom-navalha",
      tenantId: TENANT_DOM_NAVALHA,
      slug: "dom-navalha",
      categoria: "barbearia",
      identidadeVisual: {
        nome: "Barbearia Dom Navalha",
        nomeCurto: "Dom Navalha",
        logoIniciais: "DN",
        corPrincipal: "#1C1A17",
        corSecundaria: "#FAF7F2",
        corDestaque: "#B5651D",
        estilo: "Sofisticado, grafite e cobre",
        modelo: "classico",
        endereco: "Rua das Palmeiras, 245 – Centro",
        telefone: "(11) 99999-9999",
        redesSociais: { instagram: "@domnavalha" },
        textoApresentacao: "Barbearia de bairro com acabamento de navalha e atendimento sem enrolação.",
        fotos: [],
      },
      documentoFiscal: "12.345.678/0001-01",
      fusoHorario: "America/Sao_Paulo",
      horarioGeral: { diasFuncionamento: DIAS_TER_A_SAB, abertura: "09:00", fechamento: "19:00" },
      regras: regrasPadrao({ antecedenciaMinimaMinutos: 60, limiteDiasFuturos: 30, prazoCancelamentoHoras: 3 }),
      plano: "pro",
      featuresDesativadas: [],
      limites: obterDefinicaoPlano("pro").limites,
      status: "ativo",
      criadoEm: addDays(new Date(), -220).toISOString(),
      quantidadeProfissionais: 3,
    },
    {
      id: "estab-corte-certo",
      tenantId: TENANT_CORTE_CERTO,
      slug: "corte-certo",
      categoria: "barbearia",
      identidadeVisual: {
        nome: "Corte Certo Barbearia",
        nomeCurto: "Corte Certo",
        logoIniciais: "CC",
        corPrincipal: "#1C1A17",
        corSecundaria: "#FAF7F2",
        corDestaque: "#2F6F4E",
        estilo: "Moderno",
        modelo: "moderno",
        endereco: "Av. Brasil, 900 – Jardim América",
        telefone: "(11) 98888-1234",
        textoApresentacao: "Barbearia em fase de testes na plataforma.",
        fotos: [],
      },
      documentoFiscal: "23.456.789/0001-02",
      fusoHorario: "America/Sao_Paulo",
      horarioGeral: { diasFuncionamento: DIAS_SEG_A_SAB, abertura: "08:00", fechamento: "20:00" },
      regras: regrasPadrao({ antecedenciaMinimaMinutos: 30, limiteDiasFuturos: 15, prazoCancelamentoHoras: 2 }),
      plano: "essencial",
      featuresDesativadas: [],
      limites: obterDefinicaoPlano("essencial").limites,
      status: "teste",
      criadoEm: addDays(new Date(), -12).toISOString(),
      quantidadeProfissionais: 2,
    },
    {
      id: "estab-barbearia-vintage",
      tenantId: TENANT_BARBEARIA_VINTAGE,
      slug: "barbearia-vintage",
      categoria: "barbearia",
      identidadeVisual: {
        nome: "Barbearia Vintage",
        nomeCurto: "Vintage",
        logoIniciais: "BV",
        corPrincipal: "#1C1A17",
        corSecundaria: "#FAF7F2",
        corDestaque: "#8A8D91",
        estilo: "Retrô",
        modelo: "classico",
        endereco: "Rua Sete de Setembro, 88 – Centro",
        telefone: "(11) 97777-5678",
        textoApresentacao: "Estabelecimento suspenso na plataforma (demonstração).",
        fotos: [],
      },
      documentoFiscal: "34.567.890/0001-03",
      fusoHorario: "America/Sao_Paulo",
      horarioGeral: { diasFuncionamento: DIAS_TER_A_SAB, abertura: "10:00", fechamento: "20:00" },
      regras: regrasPadrao({ antecedenciaMinimaMinutos: 60, limiteDiasFuturos: 20, prazoCancelamentoHoras: 4 }),
      plano: "essencial",
      featuresDesativadas: [],
      limites: obterDefinicaoPlano("essencial").limites,
      status: "suspenso",
      motivoSuspensao: "Pagamento em atraso há mais de 30 dias.",
      criadoEm: addDays(new Date(), -400).toISOString(),
      quantidadeProfissionais: 4,
    },
    {
      id: "estab-clinica-sorriso-leve",
      tenantId: TENANT_CLINICA_SORRISO_LEVE,
      slug: "clinica-sorriso-leve",
      categoria: "clinica_odontologica",
      identidadeVisual: {
        nome: "Clínica Sorriso Leve",
        nomeCurto: "Sorriso Leve",
        logoIniciais: "SL",
        corPrincipal: "#0F3B4D",
        corSecundaria: "#8FBFA6",
        corDestaque: "#1C6E8C",
        estilo: "Clínico, limpo e acolhedor",
        modelo: "classico",
        endereco: "Av. Higienópolis, 512 – Sala 12",
        telefone: "(11) 3555-2200",
        redesSociais: { instagram: "@sorrisoleveclinica" },
        textoApresentacao: "Cuidado odontológico completo, com atendimento humano e consultas sem espera.",
        fotos: [],
      },
      documentoFiscal: "45.678.901/0001-04",
      fusoHorario: "America/Sao_Paulo",
      horarioGeral: { diasFuncionamento: DIAS_SEG_A_SEX, abertura: "08:00", fechamento: "18:00" },
      regras: regrasPadrao({
        antecedenciaMinimaMinutos: 120,
        limiteDiasFuturos: 45,
        prazoCancelamentoHoras: 24,
        permitirQualquerProfissional: false,
        exigirEmailCliente: true,
        intervaloPadraoMinutos: 10,
      }),
      plano: "equipe",
      featuresDesativadas: [],
      limites: obterDefinicaoPlano("equipe").limites,
      status: "ativo",
      criadoEm: addDays(new Date(), -60).toISOString(),
      quantidadeProfissionais: 2,
    },
    {
      id: "estab-barbearia-jr",
      tenantId: TENANT_BARBEARIA_JR,
      slug: "barbearia-jr",
      categoria: "barbearia",
      identidadeVisual: {
        nome: "Barbearia JR",
        nomeCurto: "JR",
        logoIniciais: "JR",
        corPrincipal: "#141414",
        corSecundaria: "#F5F1E8",
        corDestaque: "#D4A017",
        estilo: "Urbano e despojado",
        modelo: "moderno",
        endereco: "Rua Voluntários da Pátria, 1300 – Santana",
        telefone: "(11) 96222-8080",
        redesSociais: { instagram: "@barbeariajr" },
        textoApresentacao: "Barbearia urbana com playlist boa e horário que cabe na sua rotina.",
        fotos: [],
      },
      documentoFiscal: "56.789.012/0001-05",
      fusoHorario: "America/Sao_Paulo",
      horarioGeral: { diasFuncionamento: DIAS_SEG_A_SAB, abertura: "10:00", fechamento: "21:00" },
      regras: regrasPadrao({ antecedenciaMinimaMinutos: 30, limiteDiasFuturos: 30, prazoCancelamentoHoras: 2 }),
      plano: "equipe",
      // Exceção do master: mesmo o plano Equipe incluindo relatórios, este tenant
      // específico está com o módulo desativado (demonstra a regra 2 do cálculo
      // de acesso — exceção do master vence o que o plano incluiria).
      featuresDesativadas: ["relatorios"],
      limites: obterDefinicaoPlano("equipe").limites,
      status: "ativo",
      criadoEm: addDays(new Date(), -45).toISOString(),
      quantidadeProfissionais: 2,
    },
    {
      id: "estab-barbeiro-bastiao",
      tenantId: TENANT_BARBEIRO_BASTIAO,
      slug: "barbeiro-bastiao",
      categoria: "barbearia",
      identidadeVisual: {
        nome: "Barbeiro Bastião",
        nomeCurto: "Bastião",
        logoIniciais: "BB",
        corPrincipal: "#2B2321",
        corSecundaria: "#EFE6DA",
        corDestaque: "#6B4226",
        estilo: "Artesanal, um profissional só",
        modelo: "classico",
        endereco: "Rua dos Ipês, 45 – Vila Ipê",
        telefone: "(11) 95111-4433",
        textoApresentacao: "Corte e barba feitos com calma, na cadeira do próprio Bastião.",
        fotos: [],
      },
      documentoFiscal: undefined,
      fusoHorario: "America/Sao_Paulo",
      horarioGeral: { diasFuncionamento: DIAS_TER_A_SAB, abertura: "09:00", fechamento: "18:00" },
      regras: regrasPadrao({ antecedenciaMinimaMinutos: 60, limiteDiasFuturos: 20, prazoCancelamentoHoras: 3 }),
      plano: "essencial",
      featuresDesativadas: [],
      // Override do master: plano Essencial permite até 2 profissionais, mas este
      // tenant é um barbeiro autônomo — limite ajustado para 1.
      limites: { ...obterDefinicaoPlano("essencial").limites, maxProfissionais: 1 },
      status: "ativo",
      criadoEm: addDays(new Date(), -90).toISOString(),
      quantidadeProfissionais: 1,
    },
  ];
}

export function gerarUnidadesSeed(): Unidade[] {
  return [
    { id: "unidade-dom-navalha", tenantId: TENANT_DOM_NAVALHA, nome: "Unidade Centro", endereco: "Rua das Palmeiras, 245 – Centro", principal: true },
    { id: "unidade-clinica-sorriso-leve", tenantId: TENANT_CLINICA_SORRISO_LEVE, nome: "Unidade Higienópolis", endereco: "Av. Higienópolis, 512 – Sala 12", principal: true },
    { id: "unidade-barbearia-jr", tenantId: TENANT_BARBEARIA_JR, nome: "Unidade Santana", endereco: "Rua Voluntários da Pátria, 1300 – Santana", principal: true },
    { id: "unidade-barbeiro-bastiao", tenantId: TENANT_BARBEIRO_BASTIAO, nome: "Unidade Vila Ipê", endereco: "Rua dos Ipês, 45 – Vila Ipê", principal: true },
  ];
}

/** Modelado para evolução futura (ver docs/plans/refatoracao-multinicho.md): existe
 * apenas como dado simulado, sem tela própria e sem entrar no motor de
 * disponibilidade — bloqueio simultâneo de recursos ainda não é verificado. */
export function gerarRecursosSeed(): Recurso[] {
  return [
    { id: "recurso-cadeira-1", tenantId: TENANT_DOM_NAVALHA, nome: "Cadeira 1", tipo: "cadeira", ativo: true },
    { id: "recurso-cadeira-2", tenantId: TENANT_DOM_NAVALHA, nome: "Cadeira 2", tipo: "cadeira", ativo: true },
    { id: "recurso-cadeira-3", tenantId: TENANT_DOM_NAVALHA, nome: "Cadeira 3", tipo: "cadeira", ativo: true },
    { id: "recurso-consultorio-1", tenantId: TENANT_CLINICA_SORRISO_LEVE, nome: "Consultório 1", tipo: "consultorio", ativo: true },
    { id: "recurso-consultorio-2", tenantId: TENANT_CLINICA_SORRISO_LEVE, nome: "Consultório 2", tipo: "consultorio", ativo: true },
  ];
}
