// Dados simulados dos serviços oferecidos por cada tenant.

import type { Servico } from "../types";
import { TENANT_BARBEARIA_JR, TENANT_BARBEIRO_BASTIAO, TENANT_CLINICA_SORRISO_LEVE, TENANT_DOM_NAVALHA } from "./shared";

export function gerarServicosSeed(): Servico[] {
  return [
    {
      id: "serv-corte-tradicional",
      tenantId: TENANT_DOM_NAVALHA,
      nome: "Corte tradicional",
      descricaoCurta: "Corte na tesoura e máquina, acabamento na navalha.",
      precoCentavos: 4000,
      precoVisivel: true,
      duracaoMinutos: 30,
      intervaloPosteriorMinutos: 0,
      modalidade: "presencial",
      profissionaisIds: ["prof-joao-silva", "prof-pedro-martins"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-corte-degrade",
      tenantId: TENANT_DOM_NAVALHA,
      nome: "Corte degradê",
      descricaoCurta: "Degradê navalhado com acabamento personalizado.",
      precoCentavos: 5000,
      precoVisivel: true,
      duracaoMinutos: 45,
      intervaloPosteriorMinutos: 5,
      modalidade: "presencial",
      profissionaisIds: ["prof-joao-silva", "prof-pedro-martins", "prof-rafael-costa"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-barba",
      tenantId: TENANT_DOM_NAVALHA,
      nome: "Barba",
      descricaoCurta: "Toalha quente, navalha e hidratação.",
      precoCentavos: 3000,
      precoVisivel: true,
      duracaoMinutos: 30,
      intervaloPosteriorMinutos: 0,
      modalidade: "presencial",
      profissionaisIds: ["prof-joao-silva", "prof-pedro-martins", "prof-rafael-costa"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-corte-barba",
      tenantId: TENANT_DOM_NAVALHA,
      nome: "Corte + barba",
      descricaoCurta: "Combo completo com acabamento na navalha.",
      precoCentavos: 7000,
      precoVisivel: true,
      duracaoMinutos: 60,
      intervaloPosteriorMinutos: 10,
      modalidade: "presencial",
      profissionaisIds: ["prof-joao-silva", "prof-pedro-martins", "prof-rafael-costa"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-corte-infantil",
      tenantId: TENANT_DOM_NAVALHA,
      nome: "Corte infantil",
      descricaoCurta: "Corte para crianças até 10 anos, com paciência extra.",
      precoCentavos: 3500,
      precoVisivel: true,
      duracaoMinutos: 30,
      intervaloPosteriorMinutos: 0,
      modalidade: "presencial",
      profissionaisIds: ["prof-joao-silva"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-avaliacao-inicial",
      tenantId: TENANT_CLINICA_SORRISO_LEVE,
      nome: "Avaliação inicial",
      descricaoCurta: "Exame clínico completo para planejar o tratamento.",
      precoCentavos: 5000,
      precoVisivel: false,
      duracaoMinutos: 40,
      intervaloPosteriorMinutos: 10,
      modalidade: "presencial",
      profissionaisIds: ["prof-mariana-alves", "prof-lucas-ferreira"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: true,
      ativo: true,
    },
    {
      id: "serv-limpeza",
      tenantId: TENANT_CLINICA_SORRISO_LEVE,
      nome: "Limpeza",
      descricaoCurta: "Profilaxia e remoção de tártaro.",
      precoCentavos: 18000,
      precoVisivel: true,
      duracaoMinutos: 60,
      intervaloPosteriorMinutos: 10,
      modalidade: "presencial",
      profissionaisIds: ["prof-mariana-alves", "prof-lucas-ferreira"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-clareamento",
      tenantId: TENANT_CLINICA_SORRISO_LEVE,
      nome: "Clareamento",
      descricaoCurta: "Clareamento dental a laser em consultório.",
      precoVisivel: true,
      duracaoMinutos: 90,
      intervaloPosteriorMinutos: 15,
      modalidade: "presencial",
      profissionaisIds: ["prof-mariana-alves"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: true,
      ativo: true,
    },
    {
      id: "serv-jr-corte",
      tenantId: TENANT_BARBEARIA_JR,
      nome: "Corte na máquina",
      descricaoCurta: "Corte moderno na máquina com acabamento na régua.",
      precoCentavos: 4500,
      precoVisivel: true,
      duracaoMinutos: 30,
      intervaloPosteriorMinutos: 0,
      modalidade: "presencial",
      profissionaisIds: ["prof-jonas-ribeiro", "prof-kayky-souza"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-jr-barba",
      tenantId: TENANT_BARBEARIA_JR,
      nome: "Barba desenhada",
      descricaoCurta: "Barba alinhada e desenhada na navalha.",
      precoCentavos: 3500,
      precoVisivel: true,
      duracaoMinutos: 25,
      intervaloPosteriorMinutos: 0,
      modalidade: "presencial",
      profissionaisIds: ["prof-jonas-ribeiro"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-jr-combo",
      tenantId: TENANT_BARBEARIA_JR,
      nome: "Combo completo",
      descricaoCurta: "Corte + barba com sobrancelha incluída.",
      precoCentavos: 7500,
      precoVisivel: true,
      duracaoMinutos: 60,
      intervaloPosteriorMinutos: 10,
      modalidade: "presencial",
      profissionaisIds: ["prof-jonas-ribeiro", "prof-kayky-souza"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-bast-corte",
      tenantId: TENANT_BARBEIRO_BASTIAO,
      nome: "Corte simples",
      descricaoCurta: "Corte clássico na tesoura, com calma.",
      precoCentavos: 3500,
      precoVisivel: true,
      duracaoMinutos: 40,
      intervaloPosteriorMinutos: 5,
      modalidade: "presencial",
      profissionaisIds: ["prof-bastiao-nunes"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
    {
      id: "serv-bast-barba",
      tenantId: TENANT_BARBEIRO_BASTIAO,
      nome: "Barba",
      descricaoCurta: "Barba feita na navalha, com toalha quente.",
      precoCentavos: 2500,
      precoVisivel: true,
      duracaoMinutos: 30,
      intervaloPosteriorMinutos: 5,
      modalidade: "presencial",
      profissionaisIds: ["prof-bastiao-nunes"],
      ativoNoAgendamentoPublico: true,
      exigeConfirmacaoManual: false,
      ativo: true,
    },
  ];
}
