// Idêntico ao enum `FeatureKey` do schema.prisma original — 13 valores,
// espelhando `Feature` (13 itens) em src/lib/types.ts.
export enum FeatureKey {
  AGENDA = 'AGENDA',
  AGENDAMENTO_PUBLICO = 'AGENDAMENTO_PUBLICO',
  PROFISSIONAIS = 'PROFISSIONAIS',
  CONSUMIDORES = 'CONSUMIDORES',
  RELATORIOS = 'RELATORIOS',
  EQUIPE = 'EQUIPE',
  PERSONALIZACAO_AVANCADA = 'PERSONALIZACAO_AVANCADA',
  MULTIPLAS_UNIDADES = 'MULTIPLAS_UNIDADES',
  DOMINIO_PROPRIO = 'DOMINIO_PROPRIO',
  LISTA_DE_ESPERA = 'LISTA_DE_ESPERA',
  COMISSOES = 'COMISSOES',
  PAGAMENTOS = 'PAGAMENTOS',
  ASSINATURAS = 'ASSINATURAS',
}
