// Permissão dentro de um tenant. Os 17 valores originais do schema.prisma
// continuam inalterados; `COMISSOES_VISUALIZAR`/`COMISSOES_GERENCIAR` são
// novos nesta revisão do plano (seção 3.1), espelhando
// `"comissoes.visualizar"`/`"comissoes.gerenciar"` já existentes no union
// `Permission` de src/lib/types.ts desde a feature de comissões do frontend.
export enum Permission {
  DASHBOARD_VISUALIZAR = 'DASHBOARD_VISUALIZAR',
  AGENDA_VISUALIZAR = 'AGENDA_VISUALIZAR',
  AGENDA_GERENCIAR = 'AGENDA_GERENCIAR',
  AGENDAMENTO_CRIAR = 'AGENDAMENTO_CRIAR',
  AGENDAMENTO_EDITAR = 'AGENDAMENTO_EDITAR',
  AGENDAMENTO_CANCELAR = 'AGENDAMENTO_CANCELAR',
  PROFISSIONAIS_VISUALIZAR = 'PROFISSIONAIS_VISUALIZAR',
  PROFISSIONAIS_GERENCIAR = 'PROFISSIONAIS_GERENCIAR',
  SERVICOS_VISUALIZAR = 'SERVICOS_VISUALIZAR',
  SERVICOS_GERENCIAR = 'SERVICOS_GERENCIAR',
  CONSUMIDORES_VISUALIZAR = 'CONSUMIDORES_VISUALIZAR',
  CONSUMIDORES_GERENCIAR = 'CONSUMIDORES_GERENCIAR',
  RELATORIOS_VISUALIZAR = 'RELATORIOS_VISUALIZAR',
  EQUIPE_VISUALIZAR = 'EQUIPE_VISUALIZAR',
  EQUIPE_GERENCIAR = 'EQUIPE_GERENCIAR',
  // Novos nesta revisão (ver docs/plans/migracao-nestjs-typeorm-neon.md, seção 3.1).
  COMISSOES_VISUALIZAR = 'COMISSOES_VISUALIZAR',
  COMISSOES_GERENCIAR = 'COMISSOES_GERENCIAR',
  PERSONALIZACAO_GERENCIAR = 'PERSONALIZACAO_GERENCIAR',
  CONFIGURACOES_GERENCIAR = 'CONFIGURACOES_GERENCIAR',
}
